/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,svelte,ts}"],
  safelist: [
    // Spacing
    "mb-4",
    "mb-6",
    "mb-8",
    "mb-10",
    "mb-12",
    "mb-16",
    "mb-20",
    "mb-24",
    "mb-28",
    "mb-32",
    "mt-0.5",
    "mt-1",
    "mt-2",
    "pt-3",
    "pt-32",
    "pb-16",
    "pb-24",
    "pl-2",
    "px-2",
    "px-4",
    "px-5",
    "px-6",
    "px-10",
    "py-2",
    "py-3",
    "py-3.5",
    "py-8",
    "py-10",
    "py-12",
    "p-8",
    "p-10",
    "gap-2",
    "gap-3",
    "gap-4",
    "gap-5",
    "gap-6",
    "gap-8",
    "gap-12",
    "gap-16",
    // Colors
    "text-muted",
    "text-accent",
    "text-accent2",
    "text-white",
    "bg-bg",
    "bg-card",
    "border-border",
    "border-accent",
    "from-accent",
    "to-accent2",
    // Grid
    "grid",
    "grid-cols-1",
    "grid-cols-2",
    "md:grid-cols-2",
    "sm:grid-cols-2",
    // Flex
    "flex",
    "flex-col",
    "flex-1",
    "flex-wrap",
    "flex-shrink-0",
    "items-center",
    "items-start",
    "items-stretch",
    "self-start",
    "justify-center",
    "justify-between",
    // Typography
    "font-serif",
    "font-medium",
    "font-sans",
    "text-xs",
    "text-sm",
    "text-2xl",
    "text-5xl",
    "tracking-widest",
    "uppercase",
    "leading-relaxed",
    // Borders
    "rounded",
    "rounded-lg",
    "rounded-xl",
    "rounded-2xl",
    "rounded-full",
    "border",
    "border-[3px]",
    // Sizing
    "w-11",
    "w-12",
    "w-14",
    "w-16",
    "w-48",
    "w-60",
    "w-full",
    "w-[3px]",
    "h-0.5",
    "h-11",
    "h-14",
    "h-16",
    "h-48",
    "h-60",
    // Transitions & animation
    "transition-all",
    "transition-colors",
    "duration-200",
    "duration-700",
    "delay-150",
    "delay-200",
    "delay-300",
    "opacity-0",
    "opacity-100",
    "translate-y-0",
    "translate-y-6",
    "-translate-y-px",
    "hover:opacity-85",
    "hover:-translate-y-px",
    "hover:underline",
    "hover:border-accent",
    "hover:text-white",
    "hover:text-accent",
    // Misc
    "cursor-default",
    "cursor-not-allowed",
    "resize-none",
    "outline-none",
    "disabled:opacity-50",
    "disabled:cursor-not-allowed",
    "max-w-5xl",
    "mx-auto",
    "bg-gradient-to-r",
    "bg-clip-text",
    "text-transparent",
    "shadow-[0_0_16px_rgba(167,139,250,0.3)]",
    "focus:border-accent",
    "placeholder:text-[#444]",
    "group",
    "group-hover:border-accent",
    "group-hover:text-accent",
  ],
  theme: {
    extend: {
      colors: {
        bg: "#0d0d0f",
        card: "#141416",
        border: "#222226",
        accent: "#a78bfa",
        accent2: "#60a5fa",
        muted: "#666672",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        serif: ["Playfair Display", "serif"],
      },
    },
  },
  plugins: [],
};
