/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,svelte,ts}"],
  safelist: [
    "mb-4",
    "mb-6",
    "mb-8",
    "mb-10",
    "mb-12",
    "mb-16",
    "mb-20",
    "mb-24",
    "mb-28",
    "mb-32",
    "pt-32",
    "pb-24",
    "pb-16",
    "gap-4",
    "gap-6",
    "gap-8",
    "gap-12",
    "text-muted",
    "text-accent",
    "text-accent2",
    "bg-bg",
    "bg-card",
    "border-border",
    "border-accent",
    "from-accent",
    "to-accent2",
  ],
  theme: {
    extend: {
      colors: {
        bg: "#0d0d0f",
        card: "#141416",
        border: "#222226",
        accent: "#a78bfa",
        accent2: "#60a5fa",
        muted: "#666672",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        serif: ["Playfair Display", "serif"],
      },
    },
  },
  plugins: [],
};
